#!/bin/sh
# Alpine Linux BBR one-click script
# 支持：安装 / 查看状态 / 卸载
# 用法：
#   sh alpine-bbr.sh install
#   sh alpine-bbr.sh status
#   sh alpine-bbr.sh uninstall

BBR_SYSCTL="/etc/sysctl.d/99-bbr.conf"
BBR_MODULE="/etc/modules-load.d/bbr.conf"
BACKUP_FILE="/etc/bbr-backup.conf"

green() { printf "\033[32m%s\033[0m\n" "$1"; }
yellow() { printf "\033[33m%s\033[0m\n" "$1"; }
red() { printf "\033[31m%s\033[0m\n" "$1"; }

need_root() {
    if [ "$(id -u)" != "0" ]; then
        red "请使用 root 权限运行：sudo sh $0 install"
        exit 1
    fi
}

check_alpine() {
    if [ ! -f /etc/alpine-release ]; then
        yellow "警告：当前系统似乎不是 Alpine Linux，本脚本主要为 Alpine/OpenRC 设计。"
    fi
}

kernel_ge_49() {
    kver="$(uname -r | cut -d- -f1)"
    major="$(printf "%s" "$kver" | cut -d. -f1 | sed 's/[^0-9].*//')"
    minor="$(printf "%s" "$kver" | cut -d. -f2 | sed 's/[^0-9].*//')"

    [ -z "$major" ] && major=0
    [ -z "$minor" ] && minor=0

    if [ "$major" -gt 4 ]; then
        return 0
    fi

    if [ "$major" -eq 4 ] && [ "$minor" -ge 9 ]; then
        return 0
    fi

    return 1
}

available_cc() {
    cat /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null
}

current_cc() {
    cat /proc/sys/net/ipv4/tcp_congestion_control 2>/dev/null
}

current_qdisc() {
    cat /proc/sys/net/core/default_qdisc 2>/dev/null
}

has_bbr() {
    available_cc | grep -qw "bbr"
}

try_load_bbr() {
    if has_bbr; then
        return 0
    fi

    if command -v modprobe >/dev/null 2>&1; then
        modprobe tcp_bbr 2>/dev/null || true
    fi

    has_bbr
}

backup_current() {
    if [ ! -f "$BACKUP_FILE" ]; then
        old_cc="$(current_cc)"
        old_qdisc="$(current_qdisc)"

        {
            echo "OLD_CC=$old_cc"
            echo "OLD_QDISC=$old_qdisc"
        } > "$BACKUP_FILE"
    fi
}

enable_modules_service() {
    if command -v rc-update >/dev/null 2>&1 && [ -x /etc/init.d/modules ]; then
        rc-update add modules boot >/dev/null 2>&1 || true
    fi
}

install_bbr() {
    need_root
    check_alpine

    if ! kernel_ge_49; then
        red "当前内核版本为 $(uname -r)，BBR 通常需要 Linux 4.9+。"
        red "请先升级 Alpine 内核，例如 linux-lts / linux-virt。"
        exit 1
    fi

    if ! try_load_bbr; then
        red "当前内核没有检测到 bbr 拥塞控制算法。"
        red "可能原因：内核未启用 CONFIG_TCP_CONG_BBR，或 VPS/容器不允许加载 tcp_bbr 模块。"
        exit 1
    fi

    backup_current

    mkdir -p /etc/sysctl.d
    mkdir -p /etc/modules-load.d

    cat > "$BBR_SYSCTL" <<EOF
# Generated by alpine-bbr.sh
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF

    echo "tcp_bbr" > "$BBR_MODULE"

    enable_modules_service

    sysctl -w net.core.default_qdisc=fq >/dev/null 2>&1 || yellow "警告：设置 net.core.default_qdisc=fq 失败。"
    sysctl -w net.ipv4.tcp_congestion_control=bbr >/dev/null 2>&1 || {
        red "设置 BBR 失败。"
        exit 1
    }

    echo
    green "BBR 已开启。"
    show_status

    if command -v lbu >/dev/null 2>&1; then
        yellow "提示：如果你的 Alpine 是 diskless 模式，请执行：lbu commit -d"
    fi
}

restore_old_value() {
    old_cc=""
    old_qdisc=""

    if [ -f "$BACKUP_FILE" ]; then
        old_cc="$(grep '^OLD_CC=' "$BACKUP_FILE" | cut -d= -f2-)"
        old_qdisc="$(grep '^OLD_QDISC=' "$BACKUP_FILE" | cut -d= -f2-)"
    fi

    if [ -n "$old_cc" ] && available_cc | grep -qw "$old_cc"; then
        sysctl -w "net.ipv4.tcp_congestion_control=$old_cc" >/dev/null 2>&1 || true
    else
        if available_cc | grep -qw "cubic"; then
            sysctl -w net.ipv4.tcp_congestion_control=cubic >/dev/null 2>&1 || true
        elif available_cc | grep -qw "reno"; then
            sysctl -w net.ipv4.tcp_congestion_control=reno >/dev/null 2>&1 || true
        fi
    fi

    if [ -n "$old_qdisc" ]; then
        sysctl -w "net.core.default_qdisc=$old_qdisc" >/dev/null 2>&1 || true
    fi
}

uninstall_bbr() {
    need_root
    check_alpine

    rm -f "$BBR_SYSCTL"
    rm -f "$BBR_MODULE"

    restore_old_value

    echo
    green "BBR 配置已删除，并已尝试恢复安装前的配置。"
    show_status

    if command -v lbu >/dev/null 2>&1; then
        yellow "提示：如果你的 Alpine 是 diskless 模式，请执行：lbu commit -d"
    fi
}

show_status() {
    echo "========== BBR 状态 =========="
    echo "系统版本：$(cat /etc/alpine-release 2>/dev/null || echo unknown)"
    echo "内核版本：$(uname -r)"
    echo "可用算法：$(available_cc)"
    echo "当前算法：$(current_cc)"
    echo "当前队列：$(current_qdisc)"
    echo

    if has_bbr; then
        echo "BBR 支持：是"
    else
        echo "BBR 支持：否"
    fi

    if [ "$(current_cc)" = "bbr" ]; then
        green "BBR 状态：已启用"
    else
        yellow "BBR 状态：未启用"
    fi

    echo
    echo "sysctl 配置：$BBR_SYSCTL"
    if [ -f "$BBR_SYSCTL" ]; then
        echo "持久化 sysctl：已写入"
    else
        echo "持久化 sysctl：未写入"
    fi

    echo
    echo "模块配置：$BBR_MODULE"
    if [ -f "$BBR_MODULE" ]; then
        echo "持久化模块：已写入"
    else
        echo "持久化模块：未写入"
    fi
    echo "=============================="
}

menu() {
    echo "Alpine BBR 一键脚本"
    echo "1) 开启 BBR"
    echo "2) 查看状态"
    echo "3) 卸载 BBR 配置"
    echo "0) 退出"
    printf "请选择："
    read ans

    case "$ans" in
        1) install_bbr ;;
        2) show_status ;;
        3) uninstall_bbr ;;
        0) exit 0 ;;
        *) red "无效选择" ;;
    esac
}

case "${1:-menu}" in
    install|enable|on)
        install_bbr
        ;;
    status|check)
        show_status
        ;;
    uninstall|remove|off)
        uninstall_bbr
        ;;
    menu)
        menu
        ;;
    *)
        echo "用法："
        echo "  sh $0 install"
        echo "  sh $0 status"
        echo "  sh $0 uninstall"
        exit 1
        ;;
esac